
import type { I18nData, Scheme } from './types';

export const TRANSLATIONS: I18nData = {
  en: {
    siteName: "SchemeLink",
    tagline: "Find & apply for govt schemes",
    heroTitle: "Discover Government Schemes Matched to Your Profile",
    heroSubtitle:
      "Search by name, category, or your eligibility — quickly find scholarships, pensions, farmer support, and more.",
    searchPlaceholder: "Search schemes...",
    allRegions: "All Regions",
    search: "Search",
    popularSchemes: "Popular Schemes",
    howItWorks: "How It Works",
    benefits: "Benefits",
    uploadDocs: "Upload Documents",
    uploadHint: "Select a scheme and attach required files (e.g., Aadhaar, income proof, certificates).",
    uploadBtn: "Upload Files",
    uploading: "Uploading...",
    aboutTitle: "About SchemeLink",
    aboutText:
      "SchemeLink helps citizens discover welfare programs they qualify for and simplifies the application process. This demo is a client-side prototype.",
    apply: "Apply",
    fundLabel: "Fund Amount",
    testimonials: "What Users Say",
    home: "Home",
    how: "How",
    schemes: "Schemes",
    about: "About",
    selectScheme: "Select Scheme",
    attachFiles: "Attach Files",
    files: "Files",
  },
  ta: {
    siteName: "ஸ்கீம் லிங்க்",
    tagline: "அரசு திட்டங்களை கண்டறிந்து விண்ணப்பிக்க",
    heroTitle: "உங்கள் சுயவிவரத்திற்கு பொருத்தமான அரசுத் திட்டங்களை கண்டறியுங்கள்",
    heroSubtitle:
      "பெயர், வகை அல்லது தகுதிக்கேற்ப தேடவும் — உதவித்தொகை, ஓய்வூதியம், விவசாய உதவிகள் மற்றும் மேலும்.",
    searchPlaceholder: "திட்டங்களைத் தேடு...",
    allRegions: "அனைத்து மண்டலங்கள்",
    search: "தேடு",
    popularSchemes: "பிரபலமான திட்டங்கள்",
    howItWorks: "எப்படி வேலை செய்கிறது",
    benefits: "பலன்கள்",
    uploadDocs: "ஆவணங்களை பதிவேற்றுக",
    uploadHint: "திட்டத்தைத் தேர்ந்தெடுத்து கோப்புகளை இணைக்கவும் (ஆதார், வருமான சான்றிதழ்).",
    uploadBtn: "பதிவேற்றுக",
    uploading: "பதிவேற்றுகிறது...",
    aboutTitle: "ஸ்கீம் லிங்க் பற்றி",
    aboutText:
      "ஸ்கீம் லிங்க் குடிமக்கள் தகுதியுள்ள நலத் திட்டங்களைக் கண்டறிந்து விண்ணப்ப செயல்முறையை எளிதாக்க உதவுகிறது. இது ஒரு டெமோ மட்டுமே.",
    apply: "விண்ணப்பிக்க",
    fundLabel: "நிதி தொகை",
    testimonials: "பயனர்கள் என்ன சொல்கிறார்கள்",
    home: "முகப்பு",
    how: "எப்படி",
    schemes: "திட்டங்கள்",
    about: "பற்றி",
    selectScheme: "திட்டத்தைத் தேர்ந்தெடுக்கவும்",
    attachFiles: "கோப்புகளை இணைக்கவும்",
    files: "கோப்புகள்",
  },
  hi: {
    siteName: "स्कीमलिंक",
    tagline: "सरकारी योजनाएँ खोजें और आवेदन करें",
    heroTitle: "आपकी प्रोफ़ाइल के लिए उपयुक्त सरकारी योजनाएँ खोजें",
    heroSubtitle:
      "नाम, श्रेणी या पात्रता के अनुसार खोजें — छात्रवृत्ति, पेंशन, किसान सहायता और अधिक।",
    searchPlaceholder: "योजनाएँ खोजें...",
    allRegions: "सभी क्षेत्र",
    search: "खोजें",
    popularSchemes: "लोकप्रिय योजनाएँ",
    howItWorks: "यह कैसे काम करता है",
    benefits: "लाभ",
    uploadDocs: "दस्तावेज़ अपलोड करें",
    uploadHint: "योजना चुनें और फाइलें संलग्न करें (आधार, आय प्रमाण पत्र).",
    uploadBtn: "अपलोड करें",
    uploading: "अपलोड हो रहा है...",
    aboutTitle: "स्कीमलिंक के बारे में",
    aboutText:
      "स्कीमलिंक नागरिकों को उनकी योग्यता के अनुसार योजनाएँ खोजने और आवेदन करने में मदद करता है। यह एक क्लाइंट-साइड डेमो है।",
    apply: "आवेदन करें",
    fundLabel: "फंड राशि",
    testimonials: "उपयोगकर्ता क्या कहते हैं",
    home: "होम",
    how: "कैसे",
    schemes: "योजनाएं",
    about: "बारे में",
    selectScheme: "योजना चुनें",
    attachFiles: "फ़ाइलें संलग्न करें",
    files: "फ़ाइलें",
  },
};

export const SAMPLE_SCHEMES: Scheme[] = [
  {
    id: 1,
    title: "Post-Matric Scholarship",
    emoji: "🎓",
    region: "Central",
    desc: "Financial help for students from reserved categories pursuing higher education.",
    fund: "₹10,000 – ₹30,000 per year",
    tags: ["Students", "Education"],
  },
  {
    id: 2,
    title: "PM Kisan",
    emoji: "🌾",
    region: "Central",
    desc: "Income support for marginal farmers for cultivation expenses.",
    fund: "₹6,000 per year (₹2,000 every 4 months)",
    tags: ["Farmers", "Income"],
  },
  {
    id: 3,
    title: "Senior Citizen Pension",
    emoji: "👵",
    region: "State",
    desc: "Monthly pension for eligible elderly citizens under state welfare programs.",
    fund: "₹1,000 – ₹2,500 per month",
    tags: ["Senior", "Pension"],
  },
  {
    id: 4,
    title: "National Urban Livelihood Mission",
    emoji: "🏙️",
    region: "Central",
    desc: "Skill training and livelihood support for urban poor households.",
    fund: "Variable — skill stipend plus placement support",
    tags: ["Employment", "Skills"],
  },
  {
    id: 5,
    title: "Student Loan Subsidy",
    emoji: "📚",
    region: "Central",
    desc: "Interest subsidy on education loans for economically weaker students.",
    fund: "Interest subsidy during moratorium period",
    tags: ["Students", "Loans"],
  },
  {
    id: 6,
    title: "Women Self Help Grants",
    emoji: "👩‍🦰",
    region: "State",
    desc: "Seed grants and training for women-led small businesses.",
    fund: "₹15,000 – ₹50,000 startup grants",
    tags: ["Women", "Entrepreneurship"],
  },
  {
    id: 7,
    title: "Rural Housing Scheme",
    emoji: "🏡",
    region: "Central",
    desc: "Financial support for constructing pucca houses for eligible rural families.",
    fund: "₹1,20,000 – ₹1,50,000 per house",
    tags: ["Housing", "Rural"],
  },
  {
    id: 8,
    title: "Health Insurance Support",
    emoji: "🩺",
    region: "Central",
    desc: "Free/subsidized health insurance for low-income households.",
    fund: "₹50,000 – ₹2,00,000 coverage",
    tags: ["Health", "Insurance"],
  },
  {
    id: 9,
    title: "Skill India Apprenticeship",
    emoji: "🛠️",
    region: "Central",
    desc: "Apprenticeships and stipends for youth to learn industry skills.",
    fund: "Monthly stipend + placement assistance",
    tags: ["Skills", "Youth"],
  },
];
